version: "3.9"

services:
  app:
    image: ghcr.io/danieleramacci/app-disp-gruppo:latest
    container_name: app-disp-gruppo
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.app.rule=Host(`gruppo.easydigitalagency.it`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.middlewares.app-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.app.middlewares=app-https-redirect"

      - "traefik.http.routers.app-secure.rule=Host(`gruppo.easydigitalagency.it`)"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.tls.certresolver=myresolver"
    restart: unless-stopped

networks:
  traefik-net:
    external: true
