version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      # Dashboard
      - --api.dashboard=true
      - --api.insecure=true   # ATTENZIONE: solo per test, accesso senza password

      # EntryPoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy

      # Let's Encrypt (HTTP challenge)
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=tuo@email.it
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

    ports:
      - 80:80
      - 443:443
      - 8081:8080   # dashboard traefik

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt

    networks:
      - proxy

    restart: unless-stopped

  app:
    image: ghcr.io/danieleramacci/app-disp-gruppo:latest
    container_name: app-disp-gruppo
    networks:
      - proxy
    labels:
      - traefik.enable=true

      # Redirect HTTP → HTTPS
      - traefik.http.routers.app.rule=Host(`gruppo.easydigitalagency.it`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.middlewares.app-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.app.middlewares=app-https-redirect

      # Router HTTPS
      - traefik.http.routers.app-secure.rule=Host(`gruppo.easydigitalagency.it`)
      - traefik.http.routers.app-secure.entrypoints=websecure
      - traefik.http.routers.app-secure.tls.certresolver=myresolver

      # Porta interna dell'app (server.py ascolta su 5000)
      - traefik.http.services.app.loadbalancer.server.port=5000

    restart: unless-stopped

volumes:
  traefik_data:

networks:
  proxy:
    name: proxy
